services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3308:3306

  web:
    build:
      context: .
      shm_size: '1gb' 
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/v3_advanced_rails:delegated
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/app/node_modules:cached
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
    environment:
      TZ: Asia/Tokyo
      SELENIUM_DRIVER_URL: http://chrome:4455/wd/hub
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
      - elasticsearch
      - mailcatcher

  chrome:
    image: seleniarm/standalone-chromium:latest
    shm_size: 512m
    ports:
      - 4455:4444

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    volumes:
      - es_data:/usr/share/elasticsearch/data  # Elasticsearchのデータを永続化
    ports:
      - "9200:9200"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"  # Webインターフェース
      - "1025:1025"  # SMTPサーバー（ローカルホスト上では1025を使用）
    networks:
      - default

volumes:
  mysql_data:
  bundle_data:
  node_modules:
  es_data:  # 追加されたElasticsearch用のボリューム
