default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: v3_advanced_rails_development
  username: root
  password: password
  host: db

test:
  <<: *default
  database: v3_advanced_rails_test
  username: root
  password: password
  host: db

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
