name: RSpec CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: v3_advanced_rails_test
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
        ports:
          - 9200:9200
        env:
          discovery.type: single-node

    env:
      RAILS_ENV: test
      ELASTICSEARCH_URL: http://localhost:9200

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: Set up Database
        run: |
          sudo apt-get install libpq-dev
          chmod +x bin/rails
          cp config/database.yml.ci config/database.yml
          RAILS_ENV=test bin/rails db:create db:schema:load

      - name: Run RSpec
        run: bin/rspec
